<?php

$lotteries_info = [
   '19:00' => [['lottery_name'=>'belgium_3d','lottery_type' => '3D','link_url'=> 'https://www.nationale-loterij.be/onze-spelen/pick3/uitslagen-trekking/13-08-2023?', 'period' => 1,'start_end' => '19:00', 'num_mins_per_period' => '', 'country' => 'Belgium', 'timezone' => 'Europe/Brussels', 'table_name' => 'belgium_3d_1kb',]],      
   '21:15' => [['lottery_name'=>'china_3d','lottery_type' => '3D','link_url'=> 'https://sports.sina.com.cn/l/kaijiang/detail.shtml?game=102', 'period' => 1,'start_end' => '21:15', 'num_mins_per_period' => '', 'country' => 'beijing', 'timezone' => 'Asia/Shanghai' , 'table_name' => 'china_3d_1kb']],     
   '21:30' => [['lottery_name'=>'china_happy8','lottery_type' => 'Keno','link_url'=> 'https://sports.sina.com.cn/l/kaijiang/detail.shtml?game=104', 'period' => 1,'start_end' => '21:30', 'num_mins_per_period' => '', 'country' => 'beijing', 'timezone' => 'Asia/Shanghai','table_name' => 'china_happy_1kb']],   
   '21:25' => [['lottery_name'=>'china_7_stars','lottery_type' => '7D','link_url'=> 'https://sports.sina.com.cn/l/kaijiang/detail.shtml?game=204', 'period' => 1,'start_end' => '21:25', 'num_mins_per_period' => 'Tuesday,Friday,Sunday', 'country' => 'beijing', 'timezone' => 'Asia/Shanghai','table_name' => 'china_7_stars'],['lottery_name'=>'china_p5','lottery_type' => '5D','link_url'=> 'https://sports.sina.com.cn/l/kaijiang/detail.shtml?game=203', 'period' => 1,'start_end' => '21:25', 'num_mins_per_period' => '', 'country' => 'beijing', 'timezone' => 'Asia/Shanghai','table_name' => 'china_ps_1kb']],       
   '20:30' => [['lottery_name'=>'taiwan_3d','lottery_type' => '3D','link_url'=> 'https://www.taiwanlottery.com/lotto/result/3_d', 'period' => 1,'start_end' => '21:30', 'num_mins_per_period' => '','nums_mins_per_period_stop_day' => 'Sunday', 'country' => 'taiwan', 'timezone' => 'Asia/Shanghai','table_name' => 'taiwan_3d_1kb'],['lottery_name'=>'taiwan_4d','lottery_type' => '4D','link_url'=> 'https://www.taiwanlottery.com/lotto/result/4_d', 'period' => 1,'start_end' => '21:30', 'num_mins_per_period' => '','nums_mins_per_period_stop_day' => 'Sunday', 'country' => 'taiwan', 'timezone' => 'Asia/Taipei', 'table_name' => 'taiwan_4d_1kb'], ['lottery_name'=>'taiwan_lotto','lottery_type' => '49x7','link_url'=> 'https://www.taiwanlottery.com/lotto/result/lotto649', 'period' => 1,'start_end' => '20:30', 'num_mins_per_period' => 'Tuesday,Friday', 'country' => 'taiwan', 'timezone' => 'Asia/Taipei', 'table_name' => 'taiwan_lotto_1kb'],['lottery_name'=>'hong_kong_mark6','lottery_type' => '49x7','link_url'=> 'https://bet.hkjc.com/marksix/Results.aspx?lang=en', 'period' => 1,'start_end' => '21:30', 'num_mins_per_period' => 'Tuesday,Thursday,Saturday', 'country' => 'HongKong', 'timezone' => 'Asia/Hong_Kong', 'table_name', 'hongkong_mark6_1kb']],      
   '07:05' => [['lottery_name'=>'taiwan_bingo','lottery_type' => 'Keno','link_url'=> 'https://www.taiwanlottery.com/lotto/result/bingo_bingo?searchData=true', 'period' => 203,'start_end' => '07:05~23:55','intervals' => 300, 'num_mins_per_period' => '', 'country' => 'taiwan', 'timezone' => 'Asia/Taipei','table_name' => 'taiwan_bingo_1kb']],
];
$lotteries_info = [
   '19:00' => [['lottery_name'=>'hong_kong_mark6','lottery_type' => '49x7','link_url'=> 'https://bet.hkjc.com/marksix/Results.aspx?lang=en', 'period' => 1,'start_end' => '21:30', 'num_mins_per_period' => 'Tuesday,Thursday,Saturday', 'country' => 'HongKong', 'timezone' => 'Asia/Hong_Kong', 'table_name'=> 'hongkong_mark6_1kb']],      
  
];

!defined('LOTTERIES_INFO') ? define('LOTTERIES_INFO',$lotteries_info) : false;