<?php

$lotteries_info = [
   '16:25' => [['lottery_name'=>'sixaus49_6_49','lottery_type' => '6/49','link_url'=> 'https://www.lotto.net/german-lotto/results/2024', 'period' => 1,'start_end' => '18:25', 'num_mins_per_period' => 'Wednesday', 'country' => 'Germany', 'timezone' => 'Europe/Berlin', 'table_name' => 'sixaus49_6_49_1kb',]],      
   '17:25' => [['lottery_name'=>'sixaus49_6_49','lottery_type' => '6/49','link_url'=> 'https://www.lotto.net/german-lotto/results/2024', 'period' => 1,'start_end' => '19:25', 'num_mins_per_period' => 'Wednesday', 'country' => 'Germany', 'timezone' => 'Europe/Berlin', 'table_name' => 'sixaus49_6_49_1kb',]],      
   '15:00' => [['lottery_name'=>'all_or_nothing_day_texas_12_24','lottery_type' => '12/24','link_url'=> 'https://www.lotterypost.com/results/tx/allornothing', 'period' => 1,'start_end' => '10:00', 'num_mins_per_period' => 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday', 'country' => 'USA', 'timezone' => 'America/Chicago', 'table_name' => 'all_or_nothing_day_texas_12_24_1kb',]],      
   '17:27' => [['lottery_name'=>'all_or_nothing_day_texas_12_24','lottery_type' => '12/24','link_url'=> 'https://www.lotterypost.com/results/tx/allornothing', 'period' => 1,'start_end' => '12:27',  'num_mins_per_period' => 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday','country' => 'USA', 'timezone' => 'America/Chicago', 'table_name' => 'all_or_nothing_day_texas_12_24_1kb',]],      
   '11:00' => [['lottery_name'=>'all_or_nothing_day_texas_12_24','lottery_type' => '12/24','link_url'=> 'https://www.lotterypost.com/results/tx/allornothing', 'period' => 1,'start_end' => '06:00',  'num_mins_per_period' => 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday', 'country' => 'USA', 'timezone' => 'America/Chicago', 'table_name' => 'all_or_nothing_day_texas_12_24_1kb',]],      
   '15:12' => [['lottery_name'=>'all_or_nothing_day_texas_12_24','lottery_type' => '12/24','link_url'=> 'https://www.lotterypost.com/results/tx/allornothing', 'period' => 1,'start_end' => '10:12',  'num_mins_per_period' => 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday', 'country' => 'USA', 'timezone' => 'America/Chicago', 'table_name' => 'all_or_nothing_day_texas_12_24_1kb',]],      
   '13:59' => [['lottery_name'=>'arizona_triple_twist_6_42','lottery_type' => '6/42','link_url'=> 'https://www.arizonalottery.com/draw-games/triple-twist/', 'period' => 1,'start_end' => '06:59', 'num_mins_per_period' => '', 'country' => 'USA', 'timezone' => 'America/Phoenix', 'table_name' => 'arizona_triple_twist_6_42_1kb',]],      
   '02:30' => [['lottery_name'=>'atlantic_6_49','lottery_type' => '6/49','link_url'=> 'https://www.alc.ca/content/alc/en/winning-numbers.html', 'period' => 1,'start_end' => '23:30', 'num_mins_per_period' => 'Wednesday,Saturday', 'country' => 'USA', 'timezone' => 'America/Halifax', 'table_name' => 'atlantic_6_49_1kb',],],   
   '17:00' => [['lottery_name'=>'belgium_3d','lottery_type' => '3D','link_url'=> 'https://www.nationale-loterij.be/onze-spelen/pick3/uitslagen-trekking/13-08-2023?', 'period' => 1,'start_end' => '19:00', 'num_mins_per_period' => '', 'country' => 'Belgium', 'timezone' => 'Europe/Brussels', 'table_name' => 'belgium_3d_1kb',]],      
   '13:15' => [['lottery_name'=>'china_3d','lottery_type' => '3D','link_url'=> 'https://sports.sina.com.cn/l/kaijiang/detail.shtml?game=102', 'period' => 1,'start_end' => '21:15', 'num_mins_per_period' => '', 'country' => 'beijing', 'timezone' => 'Asia/Shanghai' , 'table_name' => 'china_3d_1kb']], 
   '00:00' => [['lottery_name'=>'five_de_oro_5_48','lottery_type' => '5/48','link_url'=> 'https://lotterytexts.com/uruguay/5-de-oro/', 'period' => 1,'start_end' => '21:00', 'num_mins_per_period' => 'Sunday,Wednesday', 'country' => 'uruguay', 'timezone' => 'America/Montevideo' , 'table_name' => 'five_de_oro_5_48_1kb']],     
   '13:30' => [['lottery_name'=>'china_happy8','lottery_type' => 'Keno','link_url'=> 'https://sports.sina.com.cn/l/kaijiang/detail.shtml?game=104', 'period' => 1,'start_end' => '21:30', 'num_mins_per_period' => '', 'country' => 'beijing', 'timezone' => 'Asia/Shanghai','table_name' => 'china_happy8_1kb'],['lottery_name'=>'hong_kong_mark6','lottery_type' => '49x7','link_url'=> 'https://bet.hkjc.com/marksix/Results.aspx?lang=en', 'period' => 1,'start_end' => '21:30', 'num_mins_per_period' => 'Tuesday,Thursday,Saturday', 'country' => 'HongKong', 'timezone' => 'Asia/Hong_Kong', 'table_name' => 'hongkong_mark6_1kb']],   
   '13:25' => [['lottery_name'=>'china_7_stars','lottery_type' => '7D','link_url'=> 'https://sports.sina.com.cn/l/kaijiang/detail.shtml?game=204', 'period' => 1,'start_end' => '21:25', 'num_mins_per_period' => 'Tuesday,Friday,Sunday', 'country' => 'beijing', 'timezone' => 'Asia/Shanghai','table_name' => 'china_7_stars_1kb'],['lottery_name'=>'china_p5','lottery_type' => '5D','link_url'=> 'https://sports.sina.com.cn/l/kaijiang/detail.shtml?game=203', 'period' => 1,'start_end' => '21:25', 'num_mins_per_period' => '', 'country' => 'beijing', 'timezone' => 'Asia/Shanghai','table_name' => 'china_p5_1kb']],       
   '12:30' => [['lottery_name'=>'taiwan_3d','lottery_type' => '3D','link_url'=> 'https://www.taiwanlottery.com/lotto/result/3_d', 'period' => 1,'start_end' => '20:30',  'num_mins_per_period' => 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday', 'country' => 'taiwan', 'timezone' => 'Asia/Shanghai','table_name' => 'taiwan_3d_1kb'],['lottery_name'=>'taiwan_4d','lottery_type' => '4D','link_url'=> 'https://www.taiwanlottery.com/lotto/result/4_d', 'period' => 1,'start_end' => '20:30',  'num_mins_per_period' => 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday', 'country' => 'taiwan', 'timezone' => 'Asia/Taipei', 'table_name' => 'taiwan_4d_1kb'], ['lottery_name'=>'taiwan_lotto','lottery_type' => '49x7','link_url'=> 'https://www.taiwanlottery.com/lotto/result/lotto649', 'period' => 1,'start_end' => '20:30', 'num_mins_per_period' => 'Tuesday,Friday', 'country' => 'taiwan', 'timezone' => 'Asia/Taipei', 'table_name' => 'taiwan_lotto_1kb'],],  
   '23:05' => [['lottery_name'=>'taiwan_bingo','lottery_type' => 'Keno','link_url'=> 'https://www.taiwanlottery.com/lotto/result/bingo_bingo?searchData=true', 'period' => 203,'start_end' => '07:05~23:55','intervals' => 300, 'num_mins_per_period' => '', 'country' => 'taiwan', 'timezone' => 'Asia/Taipei','table_name' => 'taiwan_bingo_1kb']],
   '09:30' => [['lottery_name'=>'australia_powerball_7_35','lottery_type' => '7/35','link_url'=> 'https://australia.national-lottery.com/powerball/results', 'period' => 1,'start_end' => '19:30', 'num_mins_per_period' => 'Thursday', 'country' => 'Australia', 'timezone' => 'Australia/Sydney', 'table_name' => 'australia_powerball_1kb',]],
];

$lotteries_info = [
    '13:30' => [['lottery_name'=>'hong_kong_mark6','lottery_type' => '49x7','link_url'=> 'https://bet.hkjc.com/marksix/Results.aspx?lang=en', 'period' => 1,'start_end' => '21:30', 'num_mins_per_period' => 'Tuesday,Thursday,Saturday', 'country' => 'HongKong', 'timezone' => 'Asia/Hong_Kong', 'table_name' => 'hongkong_mark6_1kb']],
   ];

!defined('LOTTERIES_INFO') ? define('LOTTERIES_INFO',$lotteries_info) : false;